name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: >
    ${{
      (github.event_name == 'push' && format('push-{0}-rust', github.ref))
      || (github.event_name == 'pull_request' && format('pr-{0}-rust', github.event.pull_request.number))
      || (github.event_name == 'workflow_dispatch' && format('workflow-dispatch-{0}-rust', github.run_id))
      || format('{0}-rust', github.run_id)
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-24.04-32

    steps:
      - name: Tell git to do submodules in parallel
        run: |
          git config --global submodule.fetchJobs "$(nproc)"

      - name: Checkout repo and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build `build_and_test_rust` stage
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          build-args: |-
            CC=gcc-15
            CXX=g++-15
          target: build_and_test_rust
          cache-from: type=gha,scope=base_rust

      - name: Build `code_quality_rust` stage
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          target: code_quality_rust
          cache-from: type=gha,scope=base_rust

